{% set name = "APScheduler" %}
{% set version = "3.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 0db77af6400c84d1747fe98a04b8b58f0080c77d11d338c4f507a9752880f221

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools-scm >=6.4
  run:
    - python
    - tzlocal >=3.0
    - backports.zoneinfo  # [py<39]
  run_constrained:
    - protobuf <=3.21.0
    - pymongo >=3.0
    - redis >= 3.0
    - rethinkdb >=2.4.0
    - sqlalchemy >=1.4
    - tornado >=4.3

# assert 96772 != 96772
{% set deselect_tests = " --deselect=tests/test_executors.py::test_broken_pool" %}

test:
  source_files:
    - tests
  imports:
    - apscheduler
    - apscheduler.executors
    - apscheduler.jobstores
    - apscheduler.schedulers
    - apscheduler.schedulers.blocking
    - apscheduler.triggers
    - apscheduler.triggers.cron
  requires:
    - pip
    - pytest
    - pytz
    - tornado
    - anyio
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://github.com/agronholm/apscheduler
  description: |
    Advanced Python Scheduler (APScheduler) is a Python library that lets you schedule
    your Python code to be executed later, either just once or periodically.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities
  dev_url: https://github.com/agronholm/apscheduler
  doc_url: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
