{% set name = "APScheduler" %}
{% set version = "3.6.2" %}
{% set hash_type = "sha256" %}
{% set hash_val = "dcbf7ee41d7fc45b2514ad2a25e654e97162bc3af2649f230a5fb66b3f83214b" %}
{% set compress_type = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=1.70
  run:
    - python
    - setuptools
    - six >=1.4.0
    - pytz
    - tzlocal >=1.2
    - futures  # [py27]
    - funcsigs  # [py27]

test:
  imports:
    - apscheduler
    - apscheduler.executors
    - apscheduler.jobstores
    - apscheduler.schedulers
    - apscheduler.schedulers.blocking
    - apscheduler.triggers
    - apscheduler.triggers.cron

about:
  home: https://github.com/agronholm/apscheduler
  license: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities 
  dev_url: https://github.com/agronholm/apscheduler
  doc_url: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
