{% set name = "APScheduler" %}
{% set version = "3.9.0" %}
{% set hash_val = "c7a0935b4e2509393615107d9d031114b7fa4f834619b883a06ed1641cd71a51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=1.70
  run:
    - python
    - setuptools >=0.7
    - six >=1.4.0
    - pytz
    - tzlocal >=2.0,!=3.*
    - futures  # [py27]
    - funcsigs  # [py<35]
    - trollius  # [py27]
    - gevent
    - pymongo >=3.0
    - redis >=3.0
    # - rethinkdb >=2.4.0
    - sqlalchemy >=0.8
    - tornado >=4.3
    - twisted
    # - kazoo

test:
  imports:
    - apscheduler
    - apscheduler.executors
    - apscheduler.jobstores
    - apscheduler.schedulers
    - apscheduler.schedulers.blocking
    - apscheduler.triggers
    - apscheduler.triggers.cron

about:
  home: https://github.com/agronholm/apscheduler
  license: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities
  dev_url: https://github.com/agronholm/apscheduler
  doc_url: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
