{% set name = "APScheduler" %}
{% set version = "3.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6df071b27d9be898e486bc7940a7be50b4af2e9da7c08f0744a96d4bd4cef4a

build:
  skip: True  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python
    - six >=1.4.0
    - pytz
    - tzlocal >=2.0,!=3.*
    - importlib-metadata >=3.6.0  # [py<38]
  run_constrained:
    - pymongo >= 3.0
    - redis >= 3.0
    - rethinkdb >= 2.4.0
    - sqlalchemy >= 1.4
    - tornado >= 4.3

test:
  imports:
    - apscheduler
    - apscheduler.executors
    - apscheduler.jobstores
    - apscheduler.schedulers
    - apscheduler.schedulers.blocking
    - apscheduler.triggers
    - apscheduler.triggers.cron
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/agronholm/apscheduler
  description: |
    Advanced Python Scheduler (APScheduler) is a Python library that lets you schedule 
    your Python code to be executed later, either just once or periodically.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities
  dev_url: https://github.com/agronholm/apscheduler
  doc_url: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
