{% set name = "APScheduler" %}
{% set version = "3.6.3" %}
{% set hash_val = "3bb5229eed6fbbdafc13ce962712ae66e175aa214c69bed35a06bffcf0c5e244" %}
{% set compress_type = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=1.70
  run:
    - python
    - setuptools
    - six >=1.4.0
    - pytz
    - tzlocal >=1.2
    - futures  # [py27]
    - funcsigs  # [py27]
    - trollius  # [py27]

test:
  imports:
    - apscheduler
    - apscheduler.executors
    - apscheduler.jobstores
    - apscheduler.schedulers
    - apscheduler.schedulers.blocking
    - apscheduler.triggers
    - apscheduler.triggers.cron

about:
  home: https://github.com/agronholm/apscheduler
  license: MIT
  license_file: LICENSE.txt
  summary: In-process task scheduler with Cron-like capabilities 
  dev_url: https://github.com/agronholm/apscheduler
  doc_url: https://apscheduler.readthedocs.io

extra:
  recipe-maintainers:
    - ddunwoody
    - synapticarbors
