travis:
  secure:
    BINSTAR_TOKEN: ENSFqOGMzqpHeyxiIot6o+RRgpR7AQVy4bgbx6zEx9V2daF5y77dFDAWn26H+ae5RyPqW9+UIqK5Hlo6FPqYDonPGWTwt/QI8Sfd35mLrgTwTJjXB7TdjSDMpudGKVGaaSzngHEDoF4GK5NlU2SL0551k7KXkimc9w98eUfrsPrnMIzyukmZxo26dzQVXjusswD7OJ8RAAbzf+P2MDQLrEiux8xBj7ksV+tZqYMoJMIdW3JWbN/OFgmpe6y2BXwgVTTJV7GOga6QRG+Pjc0G1T/UXLoWd0g7DDyiZdbQPQJgCHHkbCXDtdrk+NsTVuiWVC31/1z7bYhUwadd+bAiOs1xUoXILnoqO3JHqS5KFlQl3Fu9Il7DlINOurRrIHZgjxgd1CnBRKOZpaJa4JG8tHVWgYq/Vw0L2JTTIalbaPERh7H2Wm5NNA3bzC2F+1HE0ZvmazP2eoymlDggERmEZ0srj5PESRqGPkalMkbBjY3SZoVP274UG/yDup7GU1fN7tpJKOxLXDPtdxYqDLrD/VJNSFfwB0ReHVud2zZXNuI/qAM9sx6fmygfc96o7LyslGvqz+NDbOCEBm1JjCDNpqalRVmk/d4kNnI9C7+Gw4HVnhtfZ/JWVrQ0JT5zwWnO6G6ZeQVxzjesoj3cs+ubHbS3Hs5fdsQ7KKSLwHjR/Ig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
