appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ARAVt+MTFbWst+YMKIQNg6bzI9jvcpznUm9hILsOotsEsGNPJhMNi7njdLPMRUHf8rJXtL8lXjFKOID24Jio0pE57QL719h8FjtSsbPy4xb7fYxVDKWVmGs8NnkWl2xskcOl5jZQU3KK5DcZJRoSHypr4qva46uxznnxmTctPdDCBdNOD1uVCih1yjHLaM2NnGiL5rtNU6FYJhIUhR4JN8nfMPwlsxcI6I2JWdlDPtNES8gTwFut/D0sVIXmkKT/jiuqD07Z9/HwRlSNQsfuUFDBcxE4vSWv1H4MYliocul4I/xDpXslhEtRIF3Mw4GiGuwEjok8w8J67zcWjHSlR03bvhYuFfvMiwD6rJEltCGHkCYsKT1RrfuQojlmwgx1PHKA4Rng/RFSGHuqQ/dpfxOnZH4CXCF1jutBKHFU8Ds0Y/DKSxlN6GBTdkqNVm8LsP2IINhJbVhvcIcQLWnS9MWmPqhKO4J/za2ZNTZWRj6kmpYfZmxkWn9FJLpg5c4G5unMoQuf+k3JUbD85vmJVEUF3P/cgJDq7LmSkwF3UCydmGoSp/IYrtqUUy1HUtK9Sdo6WD8Jq09nBGpNBUdd9F2yBd8s4/4K9sbUB6sOCJh3tX+7Ryn2GfBKsMeksMwq9nZjiWROos5r95pD1Cwt9hsOyEfi1J3VIicIjLCw0BY=}
provider:
  win: azure
conda_forge_output_validation: false
