travis:
  secure:
    BINSTAR_TOKEN: jSpZ8a8If+mryVSd5Z8bH1Z4v5uSZCRo3vZ40Lip7f1wuoVyZCw3ISrcwpFClv9aE7Smsov0KgYCGC38JzwHEfE54d93x4VFxwIe1fBzkKjrCiW4Bb5e2uW7mG2BQAzXUCJdeRKcbJysoqAVnDDT5U/f9gNdgQVZZ1CbefMgD88FN6Swb2Fe+bh+PBynD+7XHFld1TVjJzabXsdkNkUP39UeWklRI+4A8st9+ajoGmV5MApvT1bCxv+PX85hyFTAqRavYbRKLN6GKZl85VfPUVkvRNvxaa04yCMeDd9Pk9ais15augG0puZJ/JptTlNDYvkuLGFgeAXguiEjqz7qRMdX63nukTDs7fTibyPeHGK+q7y7b3NBJCaHNRk1T4mI4OlzNoW1EC39fRKu2s/RfLcqGwehMFfvQkRPh0EXQ5w5clBG38xUpHg/jk9DYC6nz2BRg020vYvLQTAsRboAt3G2sHp7B4IoYJUDG2Kj5IfdmkdLminSp8buCypdx/dLByDi+7P597RbXPf/eWij9Hc0fv3t+pIjpb+dXZvYIsd5u9b1NxuMpezvKLWuQwm8L91+1a0As3y6dsFyYZx4QSTXsNCozMH/2A6HgjUVC4sZkukXBX9svL+Y9jAKU8gmDEYY7Lj6NhEO6QLQ00taAZKDtDM+vxaU9KwUSdLfnmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
